- app/models/user.rb
has_many :gifts
has_many :friends
has_many :notes
> added associations to User Model

- app/controllers/notes_controller.rb
- test/controllers/notes_controller_test.rb
Created controller for notes with all routes - does it work? who knows! only time will tell....
> created notes controller

- app/controllers/events_controller.rb
- app/models/event.rb
- app/models/friend.rb
- app/models/user.rb
- app/views/events/edit.html.erb
- app/views/events/index.html.erb
- app/views/events/new.html.erb
- config/routes.rb
- test/controllers/events_controller_test.rb
I nested Events into Friends 🤝
This made it easier to setup create and edit forms, as this should always be associated to a Friend.
Routes and views added:
Index
Create
Edit
Destroy
No Show. Let me know if I should add it.
> Events Controller

- app/controllers/friends_controller.rb
- app/controllers/notes_controller.rb
- app/models/friend.rb
- app/views/friends/index.html.erb
- app/views/friends/new.html.erb
- app/views/friends/show.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
created the following pages
- friends show 
- friends index
- friend new
> Friends controller and view

- app/views/pages/home.html.erb
- config/environments/development.rb
Added main CTA to homepage, and links to common user journeys for logged in users only.
> Added 'add a gift CTA to homepage'

- app/assets/stylesheets/config/_colors.scss
Added global colour variables so that we can easily access the right hex colours when building out the front end
> Create global colours

- app/models/event.rb
- app/views/events/new.html.erb
Added defined event list:
To update, update the TYPES array in the Event model:
> Event list

- app/controllers/friends_controller.rb
- app/controllers/gift_ideas_controller.rb
- app/controllers/notes_controller.rb
- app/views/friends/show.html.erb
- config/routes.rb
friend's show page can show gifts (url)
friend's show page can delete note
> Edit friends showpage

- app/controllers/gift_ideas_controller.rb
- app/controllers/notes_controller.rb
- app/views/friends/show.html.erb
- app/views/notes/edit.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- remove gift idea, add remove route
- edit note
- see more gift link
> Friends show page

- app/assets/stylesheets/pages/_home.scss
- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
> Event card

- app/assets/stylesheets/pages/_home.scss
- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/pages/home.html.erb
added logic in the view (boo) so emoji is rendered based on event type
> event card emoji logic added

- app/assets/stylesheets/pages/_show_friend.scss
- app/controllers/friends_controller.rb
- app/views/friends/show.html.erb
> Friend Show Page

- app/views/gifts/index.html.erb
done part of unassigned gift section card
> Gift page frontend

- app/assets/stylesheets/pages/_show_friend.scss
- app/views/friends/show.html.erb
Updated
- Avatar Size
- Truncated Gift Idea to ensure card size is standard
- Updated Gift Idea Carousel for size
- Update Carousel to check if gift has been added already
> added larger avatar

- app/assets/stylesheets/pages/_show_friend.scss
- app/views/friends/show.html.erb
> Added Friend Default Picture / Letters

- app/views/friends/show.html.erb
You can now add a new gift from the friends page
> added new gift link to friend page

- app/views/shared/_navbar.html.erb
> Got navbar working how we want it

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/devise/sessions/new.html.erb
- app/views/events/new.html.erb
- app/views/gifts/new.html.erb
> Forms frontend

- app/views/friends/show.html.erb
Alignment tidy up and date format tidy up.
> tidy up of friend show event list and date format

- app/assets/stylesheets/application.scss
- app/javascript/packs/application.js
- app/views/pages/home.html.erb
- package.json
- yarn.lock
Upcoming events should flip on page opening 🤞
> added animate on for the home page

- app/assets/stylesheets/components/_index.scss
@Dan-Mog , commented out a line as it failed to compile can you check on Tuesday if you need the line I commented out?
Was this one: 
Line 7 in _index.scss
@import 'friendcard';
> commentated out a line in the last push

- app/views/gifts/index.html.erb
> Re-assign gift 

- app/views/friends/show.html.erb
Added padding to Avatar and increased the add event font size
Changed size of Gift Idea carousel and coloured the arrow background
> small style changes from Trello board for friend show page

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_searchform.scss
- app/views/gifts/index.html.erb
> styled the search bar

- app/views/gifts/new.html.erb
Changed it to "Haven't decided yet!"
> changed the wording on the unassigned gift

- public/404.html
- public/500.html
Updated 404 and 500 error pages - removed all of the rails style and words
> Error Pages

- app/assets/stylesheets/components/_searchform.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/gift_ideas/new.html.erb
- app/views/gifts/index.html.erb
> Gift assign frontend

- app/assets/stylesheets/components/_flip.scss
- app/views/friends/show.html.erb
Buttons etra large for when we make the card the whole width....
> increased the size of the buttons

- app/assets/stylesheets/pages/_show_friend.scss
- app/views/friends/show.html.erb
> changed the code so it won't appear twice for multiple events

- app/mailers/event_mailer.rb
- app/views/event_mailer/notify14.html.erb
- test/mailers/previews/event_mailer_preview.rb
> Updated Email CSS

- app/views/friends/show.html.erb
Friend Show Page - Links at bottom now look like buttons
> Updated text links to look like buttons

- app/assets/stylesheets/pages/_show_friend.scss
- app/views/friends/show.html.erb
New carousel design:
Also added a white background behind the Icons, maybe we want to do this to the others to make them stand out?
> Friend show carousel re-design

- app/controllers/friends_controller.rb
- app/models/friend.rb
- app/views/friends/index.html.erb
> Add a search bar on friend index

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> Changed avatar pic to Em and removed border

- app/assets/stylesheets/components/_flip.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_index_friend.scss
- app/views/friends/index.html.erb
- app/views/friends/show.html.erb
- app/views/shared/_navbar.html.erb
> Polaroid shaped styling for gift ideas to make them full width on friends show

- app/assets/stylesheets/components/_icons.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_show_friend.scss
- app/views/friends/show.html.erb
- app/views/gifts/_card_gift.html.erb
> White background on icons

- app/assets/stylesheets/pages/_index_friend.scss
- app/javascript/packs/application.js
- app/views/friends/index.html.erb
- app/views/gifts/_card_gift.html.erb
- app/views/gifts/index.html.erb
- app/views/layouts/application.html.erb
- package.json
- yarn.lock
- Edit the front end for friend index page. 
- Add the pop-up modal
- still need to add more css later.
> Friend index frontend

- app/views/friends/show.html.erb
> Style for post it note, added more margin and spaced buttons

- app/assets/stylesheets/pages/_home.scss
The link text will change to gifted pink
CTA text change to pink and bold
> Add cta  and link hover effect

- app/assets/stylesheets/pages/_show_friend.scss
- app/views/friends/show.html.erb
Added margin and padding to Other Gift Idea info section, inverted the colors with opacity added to background
> Other Gift Idea Info Bar CSS

- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/friends/show.html.erb
- app/views/pages/home.html.erb
Secondary button style, for buttons that are not main CTA.
> Added secondary button style

- app/javascript/packs/application.js
- package.json
- yarn.lock
- Changed Bootstrap back to  version 4.6
- Commented out some JS that isn't used anymore
- Added only perform AOS once per page load
> Something funky in the CSS neighbourhood

- app/assets/stylesheets/components/_flip.scss
- app/javascript/components/flip_card.js
- app/javascript/packs/application.js
- app/views/friends/show.html.erb
- Fixed overflow
- removed product name truncation
- Changed Friend Show Flip Card to a Modal
> Friend Show - Flip changed to Modal

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_flip.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_notificationcard.scss
- app/javascript/components/notification_card.js
- app/javascript/packs/application.js
- app/views/gifts/index.html.erb
- app/views/pages/home.html.erb
It currently hardcodes to one of my friend's pages so we need to figure out which page we want it to go to on the demo and I can hardcode the information.
The notification appears when you click on upcoming events
> added a popdown notification

- app/assets/stylesheets/pages/_index_friend.scss
- app/views/friends/index.html.erb
- style the friend modal
- add friend event index link
- add event new link
> Friend modal frontend

- app/views/friends/index.html.erb
> only show friends first name

- app/assets/stylesheets/components/_card.scss
- app/views/gifts/index.html.erb
> added the full page etsy cards

- app/assets/stylesheets/pages/_index_friend.scss
- app/views/friends/index.html.erb
- app/views/layouts/application.html.erb
- increase font-size
- align title center
- add the cross sign back
> Some css for friend modal

- app/assets/stylesheets/components/_icons.scss
- app/views/friends/show.html.erb
No longer any white background:
> Removed white background of icons, no longer any background

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_icons.scss
- app/views/gifts/index.html.erb
- style cta btn
- add box shadow and border-radius
- add some padding
> add some css to etsy card
